### ISSUE TITLE
Build issue with storybook 7 react vite

### ISSUE THREAD

**Issue by adrianaferrugento** [morewings/storybook-addon-theme-provider#11]
Thank you so much for building this addon, it's been a massive help!

I was trying to move to react vite and I'm seeing the following error when I run a storybook build... Don't know if you'll have any idea or even have the capacity to fix it.

![Screenshot 2023-08-17 at 17 50 20](https://github.com/morewings/storybook-addon-theme-provider/assets/76945696/9aaa743b-5053-4826-8f3b-6893522ecaa0)

**Comment by lucianobarauna** [comment]
hello i also have the same error
![image](https://github.com/morewings/storybook-addon-theme-provider/assets/1054454/72e04327-aba7-459a-9f42-a47f5ac9a755)

**Comment by morewings** [comment]
@lucianobarauna @adrianaferrugento thanks for reporting.  Seems like storybook build command doesn't support ES modules. The problem is fixed in `0.1.11` version. Sorry for the inconvenience.
