### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by pcorpet** [morewings/storybook-addon-theme-provider#20]
Please consider migrating to support storybook v8. See https://github.com/storybookjs/storybook/issues/26031

**Comment by pcorpet** [comment]
They've listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and they'd encourage you to check it out and see if your addon is impacted.

They also have an addons channel in their Discord community, which they'd like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message them (@joevaugh4n) so that they can give you the addon creator role! If you’re already in the server, please just ping them and they’ll respond to you there.

**Comment by morewings** [comment]
Hi @pcorpet. Thanks for reminder. I'm working on it. The add-on should work with 8 out of the box, but I have to bump peer dependencies versions and other minor updates. You can expect update next week.

**Comment by morewings** [comment]
Version 0.2.0 released
